apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.producer.appName }}
spec:
  replicas: {{ .Values.producer.replicaCount }}
  selector:
    matchLabels:
      app: {{ .Values.producer.appName }}
  template:
    metadata:
      labels:
        app: {{ .Values.producer.appName }}
    spec:
      containers:
      - name: broadcaster
        image: "{{ .Values.producer.image.repository }}:{{ .Values.producer.image.tag }}"
        imagePullPolicy: {{ .Values.producer.image.pullPolicy }}
        env:
        - name: KAFKA_BOOTSTRAP_SERVERS
          value: "my-cluster-kafka-bootstrap.kafka.svc.cluster.local:9092"
        - name: KAFKA_TOPIC
          value: "my-topic"