apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.producer.appName }}
  namespace: {{ .Values.namespace }}
spec:
  replicas: {{ .Values.producer.replicaCount }}
  selector:
    matchLabels:
      app: {{ .Values.producer.appName }}
  template:
    metadata:
      labels:
        app: {{ .Values.producer.appName }}
    spec:
      containers:
      - name: {{ .Values.producer.appName }}
        image: "{{ .Values.producer.image.repository }}:{{ .Values.producer.image.tag }}"
        imagePullPolicy: {{ .Values.producer.image.pullPolicy }}
        envFrom:
        - configMapRef:
            name: {{ .Values.configmap.name }}
