# Use an official Python runtime as the base image
FROM python:3.11-slim

# Set the working directory in the container
WORKDIR /app

# Copy the producer script into the container
COPY ./hello-world/producer.py .

# Install the required Python packages
RUN pip install kafka-python

# Run the producer script when the container launches
CMD ["python", "producer.py"]